export const toolSet = [
  { id: 1, name: "PHP" },
  { id: 2, name: "TypeScript" },
  { id: 3, name: "Go" },
  { id: 4, name: "Visual Studio Code" },
  { id: 5, name: "Eclipse" },
  { id: 6, name: "Sublime Text" },
  { id: 7, name: "Git" },
  { id: 8, name: "IntelliJ IDEA " },
  { id: 9, name: "Atom" },
  { id: 10, name: "NetBeans" },
  { id: 11, name: "Xcode" },
  { id: 12, name: "Notepad++" },
  { id: 13, name: "Android Studio" },
];
